language: objective-c
osx_image: xcode8
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=Example.xcodeproj
  - IOS_FRAMEWORK_SCHEME="AwesomeCache-iOS"
  - TVOS_FRAMEWORK_SCHEME="AwesomeCache-tvOS"
  - WATCHOS_FRAMEWORK_SCHEME="AwesomeCache-watchOS"
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 6"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="iphonesimulator10.0"
    # - DESTINATION="OS=9.2,name=Apple TV 1080p"     SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"
    # - DESTINATION="OS=2.2,name=Apple Watch - 42mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME" SDK="$WATCHOS_SDK"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
